### ISSUE TITLE
TypeError: null is not an object (evaluating 'react_native_1.NativeModules.RNAndroidURIPath.getPath')

### ISSUE THREAD

**Issue by alan-dx** [flyerhq/react-native-android-uri-path#1]
Hey guys, i am trying to use the package to convert an android uri to a real path, but I found this error as soon as I imported the module, any idea how to solve it?

TypeError: null is not an object (evaluating 'react_native_1.NativeModules.RNAndroidURIPath.getPath')

I just import the module and found this.

PS: I found this repository right here: (https://github.com/rnmods/react-native-document-picker/issues/70). I am facing a similar error.

**Comment by demchenkoalex** [comment]
@alan-dx Hi, sorry I totally missed this issue, I need to watch the repository :) `null is not an object` that means either NativeModules or RNAndroidURIPath is null, and you are trying calling a function on null. Both of those are related to the native module configuration, my guess that it wasn't installed properly. Can you print `RNAndroidURIPath`? It should print `null`. What version of React Native are you using? I will try to add this to the clean project and see what's going on.

**Comment by demchenkoalex** [comment]
Verified on an empty project, module is not null. Closing due to no response.
