### ISSUE TITLE
Warning: jcenter is deprecated

### ISSUE THREAD

**Issue by KROSF** [flyerhq/react-native-android-uri-path#11]
remove all references to jcenter with mavenCentral and jitpack should work perfectly

**Comment by demchenkoalex** [comment]
Oh, react native finally updated to 0.65, I guess they included that change, so I will be updating shortly :)

**Comment by demchenkoalex** [comment]
Released in [v2.2.0](https://github.com/flyerhq/react-native-android-uri-path/releases/tag/v2.2.0)
