### ISSUE TITLE
Build failed with  jvm target compatibility

### ISSUE THREAD

**Issue by ElangoPrince** [flyerhq/react-native-android-uri-path#16]
Hi, I'm facing this issue while running react-native run-android.  
 ```
Task :flyerhq_react-native-android-uri-path:compileDebugKotlin FAILED
'compileDebugJavaWithJavac' task (current target is 1.7) and 
'compileDebugKotlin' task (current target is 1.8) jvm target compatibility should be set to the same Java version.```

**Comment by demchenkoalex** [comment]
Hey, I saw you posted in the other issue that Kotlin wouldn't recognise source/sink, that was resolved? Right now, from what I could see, RN 0.65 update removed those lines (and I did in all my libraries)
```
compileOptions {
  sourceCompatibility JavaVersion.VERSION_1_8
  targetCompatibility JavaVersion.VERSION_1_8
}
```
your issue looks exactly like that. So you would need to use something that was before 0.65 update, or update your RN setup.

Also I saw that `v2.1.3` for some reason did not work for you, you can try to use `v1.0.3`, or you can just see the code and copy it over to your project, or I believe there is a way to make this work using an original `react-native-document-picker` library without this one, see this comment https://github.com/rnmods/react-native-document-picker/issues/70#issuecomment-846883668
