### ISSUE TITLE
Calling synchronous methods on native modules is not supported in Chrome.

### ISSUE THREAD

**Issue by majirosstefan** [flyerhq/react-native-android-uri-path#17]
backend.js:12688 Possible Unhandled Promise Rejection (id: 1):
Invariant Violation: Calling synchronous methods on native modules is not supported in Chrome.

![Screen Shot 2021-12-26 at 8 17 40 PM](https://user-images.githubusercontent.com/44647381/147417917-7b56ffa5-c091-4434-9a57-3aad6febd7db.png)

**Comment by demchenkoalex** [comment]
Hey @majirosstefan sorry for the late response, had health issues. What is this exactly? Is it an Android device?

**Comment by demchenkoalex** [comment]
Read about this error message a bit more, seems like it was introduced in some RN version, but I tried now on 0.67 - didn't see this error

**Comment by afilp** [comment]
I have the same problem, v0.66.2

**Comment by demchenkoalex** [comment]
https://github.com/rnmods/react-native-document-picker/issues/70#issuecomment-846883668 also mentioned in the README of the document picker repo as well, is the correct way to retrieve the path. This repo will be archived.
