### ISSUE TITLE
How this works

### ISSUE THREAD

**Issue by brunofariasd** [flyerhq/react-native-android-uri-path#18]
Hello. I am trying to use this library to convert uri to path but it just returns error.

example: 

getPath(content://com.android.externalstorage.documents/tree/primary%3AAndroid%2Fmedia)

this return:

Error: Exception in HostFunction: java.lang.UnsupportedOperationException: Unsupported Uri content://com.android.externalstorage.documents/tree/primary%3AAndroid%2Fmedia

######
RN: 0.66
Latest version lib instaled

**Comment by demchenkoalex** [comment]
Hey, sorry for the late response!

Did the update to RN 0.67 just now and tested this,

`getPath(content://com.android.providers.media.documents/document/document%3A44)`

returns

`/data/user/0/com.example/cache/temp8143442312317355734dummy.pdf`

From the error message I see that URI is not supported, maybe some files do not work that way?

Also, from the original issue thread, there were a couple suggestions after my comment, like this one https://github.com/rnmods/react-native-document-picker/issues/70#issuecomment-846883668, maybe this library is not needed at all.

**Comment by demchenkoalex** [comment]
https://github.com/rnmods/react-native-document-picker/issues/70#issuecomment-846883668 also mentioned in the README of the document picker repo as well, is the correct way to retrieve the path. This repo will be archived.
