### ISSUE TITLE
Can't get path for directory

### ISSUE THREAD

**Issue by gj94gj94ao4** [flyerhq/react-native-android-uri-path#19]
Work fine with `react-native-document-picker` to pick files and get their path.
but can't get path for a directory.
```js
const path = await pickDirectory()
if (path !== null) {
  const realPath = getPath(path.uri);
  // Error: Exception in HostFunction: java.lang.UnsupportedOperationException: Unsupported Uri 
  // content://com.android.externalstorage.documents/tree/primary%3A...
  console.log(realPath);
}
```

**Comment by demchenkoalex** [comment]
See #18 I think maybe this library is not needed at all now. I am not an Android developer, and only found this solution to pick files somewhere, not sure I will be able to adapt to directories as well.

**Comment by demchenkoalex** [comment]
https://github.com/rnmods/react-native-document-picker/issues/70#issuecomment-846883668 also mentioned in the README of the document picker repo as well, is the correct way to retrieve the path. This repo will be archived.
